### ISSUE TITLE
Bug: error when run rake on Windows machine

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#234]
### Context
- This set of messages appears when trying to run `rake` on Windows:
```
rake aborted!
Errno::ENOEXEC: Exec format error - script/build-index
C:/tools/ruby241-x64/lib/ruby/2.4.0/open3.rb:199:in `spawn'
C:/tools/ruby241-x64/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
C:/tools/ruby241-x64/lib/ruby/2.4.0/open3.rb:147:in `popen2'
c:/my-projects/scholarslab.org/Rakefile:150:in `block in <top (required)>'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
C:/tools/ruby241-x64/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
C:/tools/ruby241-x64/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
C:/tools/ruby241-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
C:/tools/ruby241-x64/bin/rake:22:in `load'
C:/tools/ruby241-x64/bin/rake:22:in `<main>'
Tasks: TOP => default => ./search_index.json
```
- **Details:**
  - It successfully deletes the _site folder, but isn't able to build the search index
  - Updated all prerequisites for site, but exact same issue happened again
    - Has consistently been the same error for a while, so isn't something that recently changed on the Windows machine
  - Does not happen on Mac OS with same codebase, so seems to be Windows-specific

### Associated Product Ticket
#2

**Comment by ZoeLeBlanc** [comment]
Woot! Fixed with one word... that doesn't happen often 🎉
